### ISSUE TITLE
Panic while running the software

### ISSUE THREAD

**Issue by bbhikkaji** [typetypetype/conntrack#9]
I am trying to play with this software but getting issues as below

panic: msg is some error: Done!. It's coming from client.go's readMsgs(). This readMsgs() is called by queryAllConnections().

How do i make this software work ?

**Comment by alicebob** [comment]
I have not use this for a while, and I get the same error when I try this on my 4.16.0 kernel.

@mallochine which kernel do you use? And/or do you do anything special?

**Comment by mallochine** [comment]
oh, no idea. That's so weird. I definitely haven't seen a panic.

Kernel is: # uname -r
4.4.77-1.el6.nutanix.20170830.145.x86_64

but, I don't think Nutanix has modified the kernel at all. So, I guess this is 4.4.77 version?

**Comment by mallochine** [comment]
what is the full panic error message? I don't understand why it's just: "Done!"

**Comment by alicebob** [comment]
Thanks for your reply, @mallochine . I'll have a proper look at this when I have a bit of time.

**Comment by bbhikkaji** [comment]
Thanks guys.

@alicebob do you need any help from my side ?

**Comment by mallochine** [comment]
could u fully print out the error? Is it really jsut "Done!"? which is a very strange error message

**Comment by bbhikkaji** [comment]
@mallochine This is full error msg i get

panic: msg is some error: Done!

**Comment by mallochine** [comment]
@alicebob do u understand it?

**Comment by alicebob** [comment]
I'll try to have a look next week, I'm traveling this week.

**Comment by alicebob** [comment]
Seems like some flag logic in the messages have changed. Weird.

I've pushed a change to master which avoids the panic. It now lists some connections, but I'm not sure it's still correct.

This code was used in a small experiment years ago. First hit on 'netlink' on godoc gives: https://github.com/vishvananda/netlink which has some conntrack stuff in there: https://github.com/vishvananda/netlink/blob/master/conntrack_linux.go  I didn't try that code, but at least it looks more maintained than this module :)
